@echo off
echo Creating backend source files...

REM Create the main app.ts file
node -e "const fs = require('fs'); const content = `import express from 'express';\nimport cors from 'cors';\nimport helmet from 'helmet';\nimport dotenv from 'dotenv';\nimport rateLimit from 'express-rate-limit';\nimport { createServer } from 'http';\nimport { Server } from 'socket.io';\n\ndotenv.config();\n\nconst app = express();\nconst httpServer = createServer(app);\nconst io = new Server(httpServer, {\n  cors: {\n    origin: process.env.CORS_ORIGIN || 'http://localhost:5173',\n    methods: ['GET', 'POST']\n  }\n});\n\n// Middleware\napp.use(helmet());\napp.use(cors({ origin: process.env.CORS_ORIGIN || 'http://localhost:5173' }));\napp.use(express.json());\napp.use(express.urlencoded({ extended: true }));\n\n// Rate limiting\nconst limiter = rateLimit({\n  windowMs: 15 * 60 * 1000,\n  max: 100\n});\napp.use('/api/', limiter);\n\n// Health check\napp.get('/health', (req, res) => {\n  res.json({ status: 'OK', timestamp: new Date().toISOString() });\n});\n\n// Import routes\nimport productsRouter from './routes/products.routes';\nimport authRouter from './routes/auth.routes';\nimport cartRouter from './routes/cart.routes';\nimport ordersRouter from './routes/orders.routes';\nimport couponsRouter from './routes/coupons.routes';\nimport referralsRouter from './routes/referrals.routes';\nimport socialProofRouter from './routes/socialProof.routes';\nimport recommendationsRouter from './routes/recommendations.routes';\nimport gamificationRouter from './routes/gamification.routes';\nimport membershipRouter from './routes/membership.routes';\n\n// Mount routes\napp.use('/api/products', productsRouter);\napp.use('/api/auth', authRouter);\napp.use('/api/cart', cartRouter);\napp.use('/api/orders', ordersRouter);\napp.use('/api/coupons', couponsRouter);\napp.use('/api/referrals', referralsRouter);\napp.use('/api/social-proof', socialProofRouter);\napp.use('/api/recommendations', recommendationsRouter);\napp.use('/api/gamification', gamificationRouter);\napp.use('/api/membership', membershipRouter);\n\n// Error handling\napp.use((err: any, req: express.Request, res: express.Response, next: express.NextFunction) => {\n  console.error(err.stack);\n  res.status(500).json({ error: 'Something went wrong!' });\n});\n\nconst PORT = process.env.PORT || 3001;\nhttpServer.listen(PORT, () => {\n  console.log(\`✓ Backend server running on port \${PORT}\`);\n  console.log(\`✓ Health check: http://localhost:\${PORT}/health\`);\n});\n\nexport { io };\n`; fs.writeFileSync('backend/src/app.ts', content);"

echo Backend files created successfully!
echo.
echo Now run: cd backend ^&^& npm run dev
echo.
pause
